name: 리팩토링
description: 코드 개선이나 구조 변경을 제안합니다
title: "[Refactor] "
labels: ["refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        코드 품질 개선이나 구조 변경을 제안해주세요.

  - type: textarea
    id: current-state
    attributes:
      label: 현재 상태
      description: 현재 코드의 어떤 부분을 개선하고 싶으신가요?
      placeholder: |
        예) BookListViewController가 너무 비대해져서 관리가 어렵습니다
        - 현재 500줄 이상
        - 네트워크, UI, 비즈니스 로직이 섞여있음
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 문제점
      description: 어떤 문제가 있나요?
      placeholder: |
        예)
        - 테스트하기 어려움
        - 코드 재사용 불가
        - 가독성 낮음
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: 개선 방안
      description: 어떻게 개선할 계획인가요?
      placeholder: |
        예)
        - ViewModel 분리
        - Repository 패턴 적용
        - 각 책임별로 파일 분리
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: 범위
      description: 리팩토링 범위
      options:
        - 전체 아키텍처
        - 특정 모듈
        - 특정 클래스/함수
    validations:
      required: true

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: 이 변경이 기존 코드를 깨뜨리나요?
      options:
        - label: 기존 API 호환성 유지
        - label: 데이터 마이그레이션 필요
        - label: 테스트 코드 수정 필요
